name: New application
description: Suggest a new application for this project.
title: "[New app]: "
labels: [new application]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new application request!
  - type: textarea
    id: feature
    attributes:
      label: "What is the new application?"
      description: "Provide clear details about the new application you want to see added to Evergreen."
      placeholder: "Provide details of the new application that could be added to Evergreen. Please add details of an update source/API (e.g. a JSON or XML source), evergreen download links etc., where current versions of this application can be queried."
    validations:
      required: true
  - type: input
    id: site
    attributes:
      label: "Vendor site"
      description: "Add a link to the official site for this application (this can be the links that lists downloads)."
      placeholder: https://www.vendor.com
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Does the vendor require a sign-in to download the app?"
      description: "If the vendor requires a sign-in to download installers, this application won't be a good candidate for Evergreen."
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Does the application include an updater?"
      description: "Applications that actively check for updates and notify the user or automatically install updates? (These applications may be good candidates for Evergreen)"
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: checkboxes
    id: documentation
    attributes:
      label: "Have you reviewed the list of supported applications?"
      description: "Please confirm that you've reviewed the list of currently supported before making this application request."
      options:
        - label: "Supported apps at: https://eucpilots.com/evergreen-docs/apps/"
          required: true
